version: "3" 
services:
  # Web service layer
  nginx:
    image: nginx:1.13
    ports:
      - "8080:80"
    volumes:
      - "./src:/src"
      - "./src/docker/config/nginx/nginx.conf:/src/docker/config/nginx/nginx.conf"
    networks: 
      - production-network
    depends_on:
      - php

  # Application service layer
  php:
    build:
      dockerfile: ./src/docker/php.dockerfile
      context: .
    volumes:
      - "./src:/src"
    ports:
      - "9000:9000"
    networks: 
      - production-network
    depends_on:
      - mysql
   
  # Data persistence service layer
  mysql:
    image: mysql:5.7.20
    networks: 
      - production-network
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123.456

networks: 
  production-network: 
    driver: bridge
